const info={
  newsInfo:{
    responseEncode:"BBM54PGAwangning",
  },
  amuseInfo:{
    responseEncode:"BA10TA81wangning",
  },
  sportInfo:{
    responseEncode:"BA8E6OEOwangning",
  },
  financeInfo:{
    responseEncode:"BA8EE5GMwangning",
  },
  warInfo:{
    responseEncode:"BAI67OGGwangning",
  },
  techInfo:{
    responseEncode:"BA8D4A3Rwangning",
  },
  mobileInfo:{
    responseEncode:"BAI6I0O5wangning",
  },
  digitalInfo:{
    responseEncode:"BAI6JOD9wangning",
  },
  fasionInfo:{
    responseEncode:"BA8F6ICNwangning",
  },
  gameInfo:{
    responseEncode:"BAI6RHDKwangning",
  },
  eduInfo:{
    responseEncode:"BA8FF5PRwangning",
  },
  healthInfo:{
    responseEncode:"BDC4QSV3wangning",
  },
  travelInfo:{
    responseEncode:"BEO4GINLwangning",
  },
}
export default info;
